config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :memories
  resources :people
  resources :relationships
  resources :static_pages, only: [:index]

  root to: 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :user

  has_many :person_memories
  has_many :people, through: :person_memories
end

app/models/person.rb
class Person < ApplicationRecord
  has_one :user
  has_many :person_memories
  has_many :memories, through: :person_memories

  has_many :relationship_memberships, foreign_key: :person_id, class_name: "RelationshipMember"
  has_many :relationships, through: :relationship_memberships
  has_many :relationship_types, through: :relationships
  has_many :related_people, through: :relationships, class_name: "Person", foreign_key: :person_id, source: :people

  def full_name
    "#{self.first_name} #{self.middle_name} #{self.last_name}"
  end

  def weight_pounds
    pounds = self.birth_weight.floor
    ounces = ( 16 * ( self.birth_weight - pounds ) ).round
    "#{ pounds } pounds, #{ ounces } ounces"
  end

  def relatives
    self.related_people
    .where( "people.id != #{self.id}" )
    .includes( :relationship_members, :relationships )
  end

  def blood_relatives
    self.related_people.joins(:relationships).joins(:relationship_types)
  end

  def parents
    self.relatives
    .where( "relationship_members.role = 'father' OR relationship_members.role = 'mother'")
  end

  def children
    self.relatives
    .where( "relationship_members.role = 'daughter' OR relationship_members.role = 'son'")
  end

  def user?
    !!self.user
  end

  def memories_about?
    self.memories.count != 0
  end

  def memories_created?
    self.user? && self.user.memories.count != 0
  end
end

app/models/person_memory.rb
class PersonMemory < ApplicationRecord
  belongs_to :person
  belongs_to :memory
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :relationship_type
  has_many :relationship_members
  has_many :people, through: :relationship_members
end

app/models/relationship_member.rb
class RelationshipMember < ApplicationRecord
  belongs_to :person
  belongs_to :relationship
end

app/models/relationship_type.rb
class RelationshipType < ApplicationRecord
  has_many :relationships
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memories
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  def index
    @memories = current_user.memories.order( memory_date: :desc )
  end

  def show
    @memory = Memory.find( params[:id] )
  end

  def new
    @memory = Memory.new
  end

  def create
    @memory = current_user.build_memory( memory_params )
    if @memory.save
      flash[:success] = "Memory created successfully."
      redirect to: memory_path( @memory )
    else
      flash[:danger] = "Memory could not be created due to errors."
      redirect to: :back
    end
  end

  def edit
    @memory = Memory.find( params[:id] )
  end

  def update
    @memory = Memory.find( params[:id] )
    if @memory.update( memory_params )
      flash[:success] = "Memory updated successfully."
      redirect to: memory_path( @memory )
    else
      flash[:danger] = "Memory could not be updated due to errors."
      redirect to: :back
    end
  end

  def destroy
    @memory = Memory.find( params[:id] )
    if @memory.destroy
      flash[:success] = "Memory deleted."
      redirect to: memories_path
    else
      flash[:danger] = "Memory could not be destroyed."
      redirect to: :back
    end
  end

  private

  def memory_params
    params.require( :memory ).permit( :user_id, :person_id, :title, :body, :memory_date )
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
    @person = current_user.person.related_people.find( params[:id] )

    if !@person
      redirect_to memories_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  skip_before_action :authenticate_user!

  def index
    redirect_to memories_path if user_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def rails_flash_to_bootstrap_class(rails_flash)
    case rails_flash
    when "notice"
      return "success"
    when "alert"
      return "danger"
    else
      return rails_flash
    end
  end

  def formatted_date(date)
    date.strftime("%B %e, %Y")
  end
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/people_helper.rb
module PeopleHelper

  def memories_created( person )
    if person.memories_created?
      render partial: "people/memories_created", locals: { person: person }
    end
  end

  def memories_about( person )
    if person.memories_about?
      render partial: "people/memories_about", locals: { person: person }
    end
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: "shared/head" %>
  </head>

  <body>

    <header>
      <%= render partial: "shared/header" %>
    </header>

    <main class="container">

      <%= render partial: "shared/flash" %>

      <%= yield %>

      <%= render partial: "shared/links" %>

    </main>

    <footer>
      <%= render partial: "shared/footer" %>
    </footer>

  </body>

</html>

app/views/memories/_memory.html.erb
<div class="memory card">
  <div class="card-block">
    <a href="<%= memory_path( memory ) %>" class="card-title">
      <h4><%= memory.title %></h4>
    </a>

    <div class="card-text">
      <% memory.people.each do |person| %>
        <a href="<%= person_path( person )%>">
          <span class="person"><%= person.first_name %> <%= person.last_name %></span>
        </a>
      <% end %>

      <p class="memdate">
        <%= formatted_date( memory.memory_date ) %>
      </p>

      <p class="membody">
        <%= memory.body %>
      </p>
    </div>
  </div>

</div>

app/views/memories/index.html.erb
<h2>All My Memories</h2>

<% @memories.each do |memory| %>

  <%= render partial: "memory", locals: { memory: memory } %>

<% end %>

app/views/memories/new.html.erb
<%= form_for @memory do |memory_fields| %>
  <div class="form-group">
    <%= memory_fields.label "Memory Date" %>
    <%= memory_fields.date_field :memory_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= memory_fields.label "Title" %>
    <%= memory_fields.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= memory_fields.label "Body" %>
    <%= memory_fields.text_area :body, class: "form-control" %>
  </div>

  <%= memory_fields.submit "Submit", class: "btn btn-outline-primary" %>
<% end %>

app/views/memories/show.html.erb
<h2><%= @memory.title %></h2>

<% @memory.people.each do |person| %>
  <a href="<%= person_path( person )%>">
    <span class="person"><%= person.first_name %> <%= person.last_name %></span>
  </a>
<% end %>

<p class="memdate">
  <%= @memory.formatted_date %>
</p>

<p class="membody">
  <%= @memory.body %>
</p>

app/views/people/_memories_about.html.erb
<h3>Memories About <%= person.first_name %></h3>

<%= render partial: "memories/memory", collection: person.memories %>

app/views/people/_memories_created.html.erb
<h3>Memories Created By <%= person.first_name %></h3>

<%= render partial: "memories/memory", collection: person.user.memories %>

app/views/people/show.html.erb
<h2><%= @person.full_name %></h2>

<p>
  Born <%= formatted_date( @person.birth_date ) %> in <%= @person.birth_place %>, weighing <%= @person.weight_pounds %>.
</p>

<%= memories_created( @person ) %>

<%= memories_about( @person ) %>

app/views/shared/_flash.html.erb
<div class="row flash-messages">
  <div class="col-xs-12">
    <% flash.each do |flash_type, flash_message| %>
      <p class="alert alert-<%= rails_flash_to_bootstrap_class( flash_type ) %>">
        <%= flash_message %>
      </p>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <div class="text-center navbar-text">
      Copyright &copy; 2016 Joshua Masland-Sarani
    </div>
  </div>
</nav>

app/views/shared/_head.html.erb
<title>BayBeeBuk</title>

<%= csrf_meta_tags %>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="x-ua-compatible" content="ie=edge">

<link href='https://fonts.googleapis.com/css?family=Oxygen:300,700,400' rel='stylesheet' type='text/css'>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">
        <span><%= image_tag "logo-64x64.png" %></span>
        <span>BayBeeBuk</span>
      </a>
    </div>

    <div class="pull-xs-right">

      <%= render partial: "shared/sign_in_out_links" %>

    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<div class="row">
  <div class="col-xs-12">
    <% if user_signed_in? %>
      <p>
        <%= link_to "All My Memories", memories_path %>
      </p>

      <p>
        <%= link_to "New Memory", new_memory_path %>
      </p>
    <% end %>
  </div>
</div>

app/views/shared/_sign_in_out_links.html.erb
<% if user_signed_in? %>

  <%= link_to current_user.person.full_name, person_path( current_user.person ), class: "navbar-text" %>

  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>

<% else %>

  <a href="<%= new_user_session_path %>" class="btn btn-outline-primary">
    Sign In
  </a>

  <a href="<%= new_user_registration_path %>" class="btn btn-outline-success">
    Sign Up
  </a>

<% end %>

app/views/static_pages/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="jumbotron">
      <h1 class="display-3 text-center">Welcome to BayBeeBuk!</h1>
      <p class="lead">Create memories with the people you love.</p>
      <hr class="m-y-2">
      <p>Any time you want to save a story or a memory for posterity, you can record it here.</p>
      <p>
        It's like a physical baby book, but it's not just for babies!
      </p>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
      </p>
    </div>
  </div>
</div>

<style media="screen">
  body {
    background-image: url(<%= asset_path 'baby_background.png' %>);
    background-repeat: no-repeat;
    background-position: center top;
  }
</style>